# Route Samstag

In [1]:
from Classes_and_functions import Extractor, structure, matcher, Kulturwiki_comparer, Kulturwiki_indexer, Steinhausen_comparer, Steinhausen_indexer, table_comparer
import difflib as dl
import pandas as pd

from os import path
xml_path = path.relpath("../Data/pages_8_47.xml")


from bs4 import BeautifulSoup  
with open(xml_path, encoding='utf8') as file:   
    contents = file.read()
    soup = BeautifulSoup(contents, 'xml')

In [2]:
Freitag = Extractor('Samstag,', 'hi', 'Tulbingkogel', 'hi', 'placeName')
Freitag.extract_text_and_tags(soup)
places = Freitag.tag_list

clean_places = structure(places)
print(clean_places)
print(len(clean_places))

['Kärnthnerthor', 'Polytechnische Jnstitut', 'technologische Museum ', 'Sr. Maj. des Kaisers', 'Taubstummen=Jnstitut', 'Theresianum', 'Theresianum', 'Bahnhof der  RaaberBahn', 'Laxenburger Allee', 'Briel', 'Laxenburg', 'Mariabrunn', 'Hadersdorf', 'Poststraße', 'Penzing', 'Baumgarten', 'Hütteldorf ', 'Auhofe', 'Mariabrunn', 'kais. Forst=Akademie', 'Hadersdorf', 'Haimbach', 'hohe Wand', 'Halterthal', 'Hütteldorf', 'Tulbingkogel', 'Mauerbach', 'Tulbingkogel']
28

In [3]:
i = clean_places.index('Briel') #that is the first place of the afternoon
del clean_places[i:] # delete entrys from the afternoon (from the last place of morning until the last place before city entry) 
clean_places

['Kärnthnerthor',
 'Polytechnische Jnstitut',
 'technologische Museum ',
 'Sr. Maj. des Kaisers',
 'Taubstummen=Jnstitut',
 'Theresianum',
 'Theresianum',
 'Bahnhof der  RaaberBahn',
 'Laxenburger Allee']

In [5]:
import functools
clean_places[2:4] = [functools.reduce(lambda x, y: x + y, clean_places[2:4])]

In [6]:
place_list = matcher(clean_places)

In [7]:
coordinates =  Kulturwiki_comparer(place_list)
coordinates.head(50)

,SHAPE,ADRESSE,SEITENNAME,MATCH_SCORE,NEUE_NAMEN
OBJECTID,,,,,
284349,POINT (16.28518125227009 48.16392472344249),"13., Maygasse 25 SCHULE",Taubstummeninstitut,92,Taubstummen=Jnstitut
293015,POINT (16.374740257710602 48.19188809841415),"04., Argentinierstraße 39",Theresianumgasse,81,Theresianum
283184,POINT (16.37005091529319 48.204338546741894),"01., Maysedergasse 2",Kärntner Hof,80,Kärnthnerthor
290588,POINT (16.36272365048848 48.15097732579337),"10., Laxenburger Straße 219",Laxenburger Straße,80,Laxenburger Allee
290547,POINT (16.443216423402742 48.227232568088226),"22., Finkenweg 213A",Lange Allee,79,Laxenburger Allee
284348,POINT (16.352948276615066 48.24301558713461),"19., Hofzeile 15/5",Taubstummenanstalt,79,Taubstummen=Jnstitut
283202,POINT (16.37064303886721 48.20340074075143),"01., Walfischgasse 3",Kärntner Turm,77,Kärnthnerthor
281458,POINT (16.360759219458423 48.216368749319926),"09., Währinger Straße 10",Altes Chemisches Institut,75,Polytechnische Jnstitut
285802,POINT (16.37014518998154 48.203082076565614),"01., Kärntner Straße TIEFGARAGE",Kärntnertorbrücke,73,Kärnthnerthor
283204,POINT (16.369764904109996 48.203734558822056),"01., Philharmonikerstraße 4",Kärntnertorbastei,73,Kärnthnerthor
294715,POINT (16.37146474172945 48.205137883662225),"01., Johannesgasse 2",Kärntnerkino,72,Kärnthnerthor
290470,POINT (16.37156507147156 48.20689290247812),"01., Kärntner Straße VOR 11-15 STAND",Kärntner Straße,71,Kärnthnerthor
284352,POINT (16.369895225564456 48.198976494624944),"04., Karlsplatz 13 Technische Universität Wien",Technische Universität,71,Polytechnische Jnstitut
283205,POINT (16.369772672546855 48.20388708094463),"01., Philharmonikerstraße 4",Kärntnertortheater,71,Kärnthnerthor
290228,POINT (16.380962146054785 48.168745119288715),"10., Klausenburger Straße 24",Klausenburger Straße,70,Laxenburger Allee
284393,POINT (16.32803931302923 48.18183942856731),"12., Hufelandgasse 3",Theresienbad,70,Theresianum
284394,POINT (16.380600304354108 48.20954064473121),"01., Rosenbursenstraße 2",Theresientor,70,Theresianum
293280,POINT (16.345864596152218 48.1344850559986),"23., Vorarlberger Allee 22",Vorarlberger Allee,69,Laxenburger Allee
290469,POINT (16.371962178675748 48.20181108204521),"01., Kärntner Ring 9(HOTEL)",Kärntner Ring,69,Kärnthnerthor
290832,POINT (16.404549505928344 48.27183974670406),"21., Lundenburger Gasse 4",Lundenburger Gasse,69,Laxenburger Allee
283563,POINT (16.36931137768221 48.196223758472456),"04., Gußhausstraße 26",Neues Elektrotechnisches Institut,68,Polytechnische Jnstitut
291848,POINT (16.39386342022206 48.22801958524448),"02., Taborstraße 120",Rabensburger Straße,67,Laxenburger Allee
282867,POINT (16.391437240972525 48.19677964114164),"03., Juchgasse 22",Israelitisches Taubstummeninstitut,67,Taubstummen=Jnstitut
284392,POINT (16.357732881221725 48.25499271161495),"19., Probusgasse 19",Theresien-Hof,67,Theresianum
283198,POINT (16.37153067236079 48.20748724170359),"01., Kärntner Straße 4",Kärntner Straße 4,67,Kärnthnerthor
283249,POINT (16.347489999432014 48.20417896938421),"07., Burggasse 69",Langer Keller,67,Laxenburger Allee
283199,POINT (16.371501915651134 48.20734335972045),"01., Kärntner Straße VOR 6(KIOSK)",Kärntner Straße 6,67,Kärnthnerthor
283922,POINT (16.404767260661995 48.19756204891485),"03., Hagenmüllergasse 31(STUDENTENHEIM)",Salesianum,67,Theresianum
292966,POINT (16.371065548935185 48.19505265431772),"04., Taubstummengasse 11",Taubstummengasse,67,Taubstummen=Jnstitut
283200,POINT (16.370340899902466 48.204435497064544),"01., Kärntner Straße VOR 34(STAND)",Kärntner Straße 7,67,Kärnthnerthor
283203,POINT (16.37120097563071 48.20227372537448),"01., Kärntner Ring 5-7 RINGSTRASSENGALERIEN",Kärntner-Ring-Hof,67,Kärnthnerthor
283201,POINT (16.371484635787077 48.20725846944191),"01., Kärntner Straße 8",Kärntner Straße 8,67,Kärnthnerthor
283561,POINT (16.35662050485877 48.22099663531289),"09., Boltzmanngasse 1(CHEMISCHES INSTITUT)",Neues Chemisches Institut,67,Polytechnische Jnstitut
287009,POINT (16.317878117953793 48.19063606036112),"14., Mariahilfer Straße 212 Techn. Museum",Technisches Museum (Institution),67,Polytechnische Jnstitut
305704,POINT (16.373480143236527 48.18167517699434),"10., Laxenburger Straße 4",Lager Laxenburger Straße 4,65,Laxenburger Allee
305703,POINT (16.373810145300954 48.18424716415484),"10., Laxenburger Straße 1-5/2",Lager Laxenburger Straße 3,65,Laxenburger Allee
283185,POINT (16.371453170482326 48.20708841812514),"01., Kärntner Straße 10",Kärntner Straße 10,65,Kärnthnerthor
289286,POINT (16.405110290562664 48.19517055251714),"03., Kleingasse 2/3",Hainburger Weg,65,Laxenburger Allee
283187,POINT (16.371306041413845 48.20638960336258),"01., Neuer Markt 2",Kärntner Straße 16,65,Kärnthnerthor
283188,POINT (16.37098850183049 48.20595335118757),"01., Neuer Markt 4",Kärntner Straße 20,65,Kärnthnerthor
305705,POINT (16.37386614367689 48.183200169078816),"10., Laxenburger Straße 9",Lager Laxenburger Straße 9,65,Laxenburger Allee
283190,POINT (16.370798132671563 48.20516048008684),"01., Marco-d'Aviano-Gasse 1",Kärntner Straße 26,65,Kärnthnerthor
283191,POINT (16.37158805106205 48.20582924139944),"01., Himmelpfortgasse 2",Kärntner Straße 27,65,Kärnthnerthor
283192,POINT (16.370721744521852 48.20500285266734),"01., Kärntner Straße 28",Kärntner Straße 28,65,Kärnthnerthor
289285,POINT (16.398406187545692 48.1984590606623),"03., Hainburger Straße 35",Hainburger Straße,65,Laxenburger Allee
293727,POINT (16.40095361723701 48.28052486435449),"21., Ödenburger Straße 73-85/19",Ödenburger Straße,65,Laxenburger Allee
283197,POINT (16.370205880226816 48.20390709779573),"01., Philharmonikerstraße 2",Kärntner Straße 38,65,Kärnthnerthor
283195,POINT (16.370268795704895 48.20404044800283),"01., Maysedergasse 1",Kärntner Straße 36,65,Kärnthnerthor
283194,POINT (16.37063511971757 48.20482670231673),"01., Führichgasse 2",Kärntner Straße 30,65,Kärnthnerthor
283196,POINT (16.371037818771857 48.204879820114485),"01., Kärntner Straße 37",Kärntner Straße 37,65,Kärnthnerthor

In [8]:
coordinates_choice = coordinates.drop(coordinates[coordinates['MATCH_SCORE'] <= 79].index)
place_coord = Kulturwiki_indexer(coordinates_choice, place_list)

In [9]:
Steinhausen_coord = Steinhausen_comparer(place_list)
Steinhausen_coord.head(50)

Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '<...>']

,Toponym,Longitude,Latitude,MATCH_SCORE,NEUE_NAMEN
ID_neu,,,,,
725,Karrter Thor,16.370195,48.203544,72,Kärnthnerthor
954,Piliotisch Stift,16.375441,48.206741,62,Polytechnische Jnstitut
40,auf den GRABEN.,16.369747,48.208682,59,Bahnhof der RaaberBahn
527,Grünen Thor,16.388092,48.215954,58,Kärnthnerthor
762,Kirchner,16.375762,48.209902,57,Kärnthnerthor
726,Karstner.,16.366291,48.209836,57,Kärnthnerthor
170,Burgerl: Spital.,16.369342,48.204866,56,Laxenburger Allee
798,Kroten Thurn,16.378943,48.211167,56,Kärnthnerthor
1016,Rother Stern,16.382126,48.217837,56,Kärnthnerthor
622,Häderen,16.376944,48.210904,56,Theresianum
919,obere fallen,16.373772,48.212990,55,Laxenburger Allee
340,gelber Adler,16.377457,48.211051,55,Laxenburger Allee
901,neue Thor.,16.370517,48.213653,55,Kärnthnerthor
45,auf der LAIMB=GRUEBEN,16.358705,48.200860,55,Bahnhof der RaaberBahn
900,neue Thor,16.369621,48.214217,55,Kärnthnerthor
701,Jägerhorn,16.370080,48.207945,55,Kärnthnerthor
341,gelber Adler,16.352728,48.206614,55,Laxenburger Allee
295,Frauenberger.,16.372070,48.203690,55,Laxenburger Allee
1013,Rother Gatter,16.376209,48.208269,54,Kärnthnerthor
36,Artner,16.372320,48.206457,53,Kärnthnerthor
802,Kürner,16.369299,48.211128,53,Kärnthnerthor
1272,V: Lautenburg,16.388646,48.215167,53,Laxenburger Allee
237,drey Raaben.,16.375174,48.211323,53,Bahnhof der RaaberBahn
128,Blauer Gatter,16.386199,48.215151,53,Laxenburger Allee
1250,untere Fallen,16.378802,48.211542,53,Laxenburger Allee
1442,<...> Waffenburg,16.369748,48.209834,52,Laxenburger Allee
812,lange Haus.,16.375403,48.210672,52,Laxenburger Allee
764,Kirnreuter,16.373512,48.210500,52,Kärnthnerthor
1015,rother Krebs,16.358738,48.201093,52,Theresianum
18,Altenburg=Hoff,16.371072,48.203646,52,Laxenburger Allee
508,Grüen Thor,16.384119,48.215741,52,Kärnthnerthor
1243,Unger=Cantzley,16.373719,48.205763,52,Laxenburger Allee
1005,roth Thurn,16.376388,48.211910,52,Kärnthnerthor
832,Lorentzberg Gassel,16.378294,48.210775,51,Laxenburger Allee
46,auf der WIEN,16.365084,48.199694,51,Bahnhof der RaaberBahn
730,Kautzisch Stifft.,16.357974,48.200988,51,Polytechnische Jnstitut
942,Pauler Thor,16.368687,48.209629,50,Kärnthnerthor
1213,Stuebenthor.,16.378590,48.207739,50,Kärnthnerthor
818,Leichnamschneider,16.367800,48.210222,50,Polytechnische Jnstitut
1167,St: Hieronimi.,16.374549,48.206233,50,Theresianum
723,Karner Strassen,16.371564,48.207246,50,Kärnthnerthor
1109,Schwarzer Adler,16.377130,48.211545,50,Laxenburger Allee
164,Burg Pastey.,16.364036,48.206057,50,Laxenburger Allee
1288,von der Land Strassen,16.385466,48.205560,50,Bahnhof der RaaberBahn
727,Katzen Steig,16.374990,48.211694,50,Taubstummen=Jnstitut
1229,Thomasini:,16.375877,48.206218,50,Theresianum
245,Ehrenlehner,16.373429,48.211419,50,Kärnthnerthor
706,Jesuiter Colegium,16.378358,48.208685,50,Theresianum
1190,Stein.,16.376450,48.206154,50,Theresianum
1371,Wertemann.,16.369506,48.210939,50,Theresianum

In [10]:
Steinhausen_choice = Steinhausen_coord.drop(Steinhausen_coord[Steinhausen_coord['MATCH_SCORE'] <= 72].index)
place_Sth_coord = Steinhausen_indexer(Steinhausen_choice, place_list)

In [11]:
place_coord['SHAPE'] = place_coord['SHAPE'].str.replace(r'POINT', '', regex=True)
place_coord['SHAPE'] = place_coord['SHAPE'].str.replace(r'\)', '', regex=True)
place_coord[['Longitude', 'Latitude']] = place_coord['SHAPE'].str.extract('(\d+.\d+)\s(\d+.\d+)', expand=True)

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\sarah\AppData\Local\Temp\ipykernel_12160\1291391956.py:3: SyntaxWarning: invalid escape sequence '\d'
  place_coord[['Longitude', 'Latitude']] = place_coord['SHAPE'].str.extract('(\d+.\d+)\s(\d+.\d+)', expand=True)

In [12]:
joined_places = pd.merge(place_coord, place_Sth_coord, left_index=True, right_index=True)
joined_places = joined_places.drop(columns=["NEUE_NAMEN_y", "SHAPE"])

In [13]:
joined_places

,NEUE_NAMEN_x,ADRESSE,Longitude_x,Latitude_x,Longitude_y,Latitude_y
0,Kärnthnerthor,"01., Maysedergasse 2",16.37005091529319,48.204338546741894,NaN,NaN
1,Polytechnische Jnstitut,NaN,NaN,NaN,NaN,NaN
2,technologische Museum Sr. Maj. des Kaisers,NaN,NaN,NaN,NaN,NaN
3,Taubstummen=Jnstitut,"13., Maygasse 25 SCHULE",16.28518125227009,48.16392472344249,NaN,NaN
4,Theresianum,"04., Argentinierstraße 39",16.374740257710602,48.19188809841415,NaN,NaN
5,Theresianum,"04., Argentinierstraße 39",16.374740257710602,48.19188809841415,NaN,NaN
6,Bahnhof der RaaberBahn,NaN,NaN,NaN,NaN,NaN
7,Laxenburger Allee,"10., Laxenburger Straße 219",16.36272365048848,48.15097732579337,NaN,NaN

In [14]:
matches_sun, matches_mon, matches_tues, matches_thur, matches_fri = table_comparer(joined_places)

In [15]:
matches_sun

,NEUE_NAMEN_x,ADRESSE_x,Longitude_x,Latitude_x,Longitude_y,Latitude_y,ADRESSE_y,Sicherheit,Longitude,Latitude,Quelle,URL
0,Polytechnische Jnstitut,NaN,NaN,NaN,NaN,NaN,"04., Karlsplatz 13",hoch,16.369912,48.198888,"Wikipedia, GeoHack",https://geohack.toolforge.org/geohack.php?page...
1,Polytechnische Jnstitut,NaN,NaN,NaN,NaN,NaN,"04., Karlsplatz 13",hoch,16.369912,48.198888,KulturwikiOGD,NaN

In [17]:
matches_mon

Empty DataFrame
Columns: [NEUE_NAMEN_x, ADRESSE_x, Longitude_x_x, Latitude_x_x, Longitude_y, Latitude_y, ADRESSE_y, Sicherheit, Longitude_x_y, Latitude_x_y, Quelle, URL]
Index: []

In [16]:
matches_tues

Empty DataFrame
Columns: [NEUE_NAMEN_x, ADRESSE_x, Longitude_x, Latitude_x, Longitude_y, Latitude_y, ADRESSE_y, Sicherheit, Longitude, Latitude, Quelle, URL]
Index: []

In [18]:
matches_thur

Empty DataFrame
Columns: [NEUE_NAMEN_x, ADRESSE_x, Longitude_x, Latitude_x, Longitude_y, Latitude_y, ADRESSE_y, Sicherheit, Longitude, Latitude, Quelle, URL]
Index: []

In [19]:
matches_fri

Empty DataFrame
Columns: [NEUE_NAMEN_x, ADRESSE_x, Longitude_x, Latitude_x, Longitude_y, Latitude_y, ADRESSE_y, Sicherheit, Longitude, Latitude, Quelle, URL]
Index: []

In [20]:
joined_places.to_excel('../Data/Samstag/joined_Samstag_coord.xlsx')

In [21]:
joined_places_nn = pd.read_excel('../Data/Samstag/joined_Samstag_coord_nn.xlsx')
joined_places_nn.to_csv('../Data/Samstag/joined_Samstag_coord_nn.csv')